fixtures:
  repositories:
    epel: "https://github.com/stahnma/puppet-module-epel.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    python: "https://github.com/stankevich/puppet-python.git"
  symlinks:
    galaxy: "#{source_dir}"
